name: Code Review

on:
  pull_request:
    branches: [ main ]

jobs:
  review:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '12.x'

    - name: Install dependencies
      run: npm install

    - name: Run Lint
      run: npm run lint

    - name: Run Security Checks
      run: npm audit 

    - name: Analyze Code Quality
      run: npx sonarqube-scanner 
