name: Scheduled Maintenance

on:
    push:
      branches: [ main ]

jobs:
  maintenance:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Run maintenance script
      run: node run.js 
