name: Scheduled Maintenance

on:
    push:
      branches: [ main ]

jobs:
  maintenance:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16'

    - run: npm install
    - run: npm start
    
